ProyectoCRPCC/Areas/Admin/Controllers/ConsultaServiciosController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoCRPCC.Data.Repositorio.IRepositorio;
using ProyectoCRPCC.Models;
using ProyectoCRPCC.Models.ViewModels;
using System.Linq;

namespace ProyectoCRPCC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ConsultaServiciosController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ConsultaServiciosController(IUnidadTrabajo unidadTrabajo,
            IWebHostEnvironment hostEnvironment)
        {
            _unidadTrabajo = unidadTrabajo;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            var servicios = _unidadTrabajo.Servicios.ObtenerTodos();
            return View(servicios);
        }

        public IActionResult Upsert(int? id)
        {
            ServiciosVM serviciosVM = new ServiciosVM()
            {
                //Llena el combobox de Servicios
                Servicios= new Servicios(),
                CategoriaLista =
                  _unidadTrabajo.Categoria.ObtenerTodos().Select(c =>
                          new SelectListItem
                          {
                              Text = c.Nombre,
                              Value = c.Id.ToString()
                          }),
            };
            //actualizamos un registro Bodega existente
            serviciosVM.Servicios = _unidadTrabajo.Servicios.Obtener(id.GetValueOrDefault());
            if (serviciosVM == null)
            {
                return NotFound();
            }
            return View(serviciosVM);
        }
    }
}

ProyectoCRPCC/Areas/Admin/Views/ConsultaServicios/Index.cshtml
<br />
<br />
<br />
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h2 class="text-dark text-center"> Consulta de Servicios</h2>
        </div>
    </div>
   
</div>

<div class="p-4 border-rounded">
    <table id="tblDatos" class="table table-responsive-md table-bordered mt-2" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th style="max-width:35%;text-align:center;">NombreServicio</th>
                <th style="max-width:35%;text-align:center;">Descripcion</th>
                <th style="max-width:35%;text-align:center;">Categoria</th>
                <th style="max-width: 25%;text-align: center;">Estado</th>
                <th style="max-width: 25%;text-align: center;">Operación</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/serviciosconsulta.js"></script>
}

ProyectoCRPCC/Areas/Admin/Views/ConsultaServicios/Upsert.cshtml
@model ProyectoCRPCC.Models.ViewModels.ServiciosVM

@{

    //Layout = "~/Views/Shared/_Layout.cshtml";
    var titulo = " ";
    var imagen = " ";
}
<style>
    input {
        max-width: 7000px;
        min-width: 100px;
    }

    .etiqueta {
        width: 200px;
        text-align: right;
    }
</style>
<form method="post">
    <div class="row p-3 border-0">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    @if (Model.Servicios.Id != 0)
    {
        //Consultar
        titulo = "Consulta de Clientes";
         imagen = Model.Servicios.ImageUrl;
        
    }
    <br />
    <br />
    <br />
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <hr>
                <div class="card-header-pills rounded-circle">
                    <h4 class="card-header-title text-center font-weight-bolder">
                        @titulo
                    </h4>
                </div>

                <h5 class="card-subtitle text-center">
                    Web CRPCC
                </h5>

                <hr>

                <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="NombreServicio" id="">NombreServicio: </span>
                    <input asp-for="Servicios.NombreServicio" class="form-control" aria-label="Nombre" readonly>
                </div>

                 <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="Descripcion" id="">Descripcion: </span>
                    <input asp-for="Servicios.Descripcion" class="form-control" aria-label="Descripcion" readonly>
                </div>

                <div class="input-group mt-2">
                <span class="input-group-text etiqueta" name="Categoria" id="Categoria">Categoria</span>
                @Html.DropDownListFor(c => c.Servicios.IdCategoria,
                                            Model.CategoriaLista, "Seleccione",
                                            new { @disabled = "disabled" })                           
                </div>
                <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="Estado"
                          id="Estado">Estado:</span>
                    <select disabled asp-for="Servicios.Estado" class="form-select" aria-label="Estado" readonly>
                        <option value=true >Activo</option> 
                        <option value=false >Inactivo</option>
                    
                    </select>
                </div>
                 

                <div class="input-group mt-2">
                     <span type="file" name="files" id="files" multiple class="form-control" />
                   <input type="hidden" asp-for="Servicios.ImageUrl" class="text-danger" aria-label = "Imagen" readonly/>
                </div>
                <div class="col-12 form-control mt-2" style="border:none;">
                    
                    @if (!imagen.Equals(""))
                    {
                        <img id="image" src="@imagen"
                             class="card-img-top img-fluid rounded"
                             style="width: 200px; height: 150px;" />
                    }
                    else
                    {
                        <img id="image" src="~/imagenes/clientes/no-imagen.jpg"
                             class="card-img-bottom img-fluid rounded"
                             style="width: 200px; height: 150px;" />
                    }

              </div>

                
                 <div class="col-12 form-control mt-2" style="border:none;">
                

                <div class="form-group row pt-5">
                    <div class="col-4 offset-8">
                       
                        <div class="col">
                            <a asp-controller="ConsultaServicios"
                               asp-action="Index"
                               class="btn btn-outline-danger rounded-pill form-control">
                                <i class="fa fa-external-link"> Regresar</i>
                            </a>
                        </div>
                      
                            
                        
                                      </div>
                            </div>

                    </div>
               </div>
        </div>
    </div>

    <div class="card-body">

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    
    
    
    
    
    </script>
}