ProyectoCRPCC/Areas/Admin/Controllers/ConsultaClienteController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProyectoCRPCC.Data.Repositorio.IRepositorio;
using ProyectoCRPCC.Models;
using ProyectoCRPCC.Models.ViewModels;
using System.Linq;

namespace ProyectoCRPCC.Areas.Admin.Controllers
{
    [Area ("Admin")]
    public class ConsultaClienteController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ConsultaClienteController(IUnidadTrabajo unidadTrabajo,
             IWebHostEnvironment hostEnvironment)
        {
            _unidadTrabajo = unidadTrabajo;
            _hostEnvironment = hostEnvironment;
        }



        public IActionResult Index()
        {
            var cliente = _unidadTrabajo.Cliente.ObtenerTodos();
            return View(cliente);

        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            ClienteVM clienteVM = new ClienteVM()
            {
                //Llena el combobox de Servicios
                Cliente = new Cliente(),
                ServiciosLista =
                   _unidadTrabajo.Servicios.ObtenerTodos().Select(c =>
                           new SelectListItem
                           {
                               Text = c.NombreServicio,
                               Value = c.Id.ToString()
                           }),
            };

            if (id == null)
            {
                //Esto es para Crear nuevo Registro
                return View(clienteVM);
            }
            //Esto es para Actualizar
            clienteVM.Cliente = _unidadTrabajo.Cliente.Obtener(id.GetValueOrDefault());
            if (clienteVM.Cliente == null)
            {
                return NotFound();
            }

            return View(clienteVM);
        }
    }
}

ProyectoCRPCC/Areas/Admin/Views/ConsultaCliente/Index.cshtml
<br />
<br />
<br />
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h2 class="text-primary text-center">Consulta de Clientes</h2>
        </div>
    </div>
   
</div>

<div class="p-4 border-rounded">
    <table id="tblDatos" class="table table-responsive-md table-bordered mt-2" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th style="max-width:35%;text-align:center;">NombreCliente</th>
                <th style="max-width:35%;text-align:center;">Apellido1</th>
                <th style="max-width:35%;text-align:center;">Apellido2</th>
                <th style="max-width:20%;text-align: center;">Cedula</th>
                 <th style="max-width:20%;text-align:center;">Operacion</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/clienteconsulta.js"></script>
}

ProyectoCRPCC/Areas/Admin/Views/ConsultaCliente/Upsert.cshtml
@model ProyectoCRPCC.Models.ViewModels.ClienteVM

@{

    //Layout = "~/Views/Shared/_Layout.cshtml";
    var titulo = " ";
    var imagen = " ";
}
<style>
    input {
        max-width: 7000px;
        min-width: 100px;
    }

    .etiqueta {
        width: 200px;
        text-align: right;
    }
</style>
<form method="post">
    <div class="row p-3 border-0">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    @if (Model.Cliente.Id != 0)
    {
        //Consultar
        titulo = "Consulta de Clientes";
         imagen = Model.Cliente.ImageUrl;
        
    }
    <br />
    <br />
    <br />
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <hr>
                <div class="card-header-pills rounded-circle">
                    <h4 class="card-header-title text-center font-weight-bolder">
                        @titulo
                    </h4>
                </div>

                <h5 class="card-subtitle text-center">
                    Web CRPCC
                </h5>

                <hr>

                <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="NombreCliente" id="">NombreCliente: </span>
                    <input asp-for="Cliente.NombreCliente" class="form-control" aria-label="Nombre" readonly>
                </div>

                 <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="Apellido1" id="">Apellido1: </span>
                    <input asp-for="Cliente.Apellido1" class="form-control" aria-label="Primer Apellido" readonly>
                </div>

                <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="Apellido2" id="Apellido2">Apellido2: </span>
                    <input asp-for="Cliente.Apellido2" class="form-control" aria-label="Segundo Apellido" readonly>
                </div>

                <div class="input-group mt-2">
                 <span class="input-group-text etiqueta" name="Cedula" id="Cedula"> Cedula: </span>
                <input asp-for="Cliente.Cedula" class="form-control texto" aria-label="Cedula" readonly>
                </div>

                <div class="input-group mt-2">
                <span class="input-group-text etiqueta" name="NombreServicio" id="NombreServicio">NombreServicio</span>
                @Html.DropDownListFor(c => c.Cliente.ServicioId,
                                            Model.ServiciosLista, "Seleccione",
                                            new { @disabled = "disabled" }) 
                                            
                </div>

                <div class="input-group mt-2">
                 <span class = "input-group-text etiqueta" name ="Direccion" id="Direccion">Direccion</span>
                 <input asp-for = "Cliente.Direccion" class=form-control texto" aria-label = "Direccion" readonly />
                </div>

                <div class="input-group mt-2">
                 <span class = "input-group-text etiqueta" name ="CodigoPostal" id="CodigoPostal">CodigoPostal</span>
                 <input asp-for = "Cliente.CodigoPostal" class=form-control texto" aria-label = "Codigo Postal" readonly />
                </div>

                <div class="input-group mt-2">
                 <span class = "input-group-text etiqueta" name ="Email" id="Email">Email</span>
                 <input asp-for = "Cliente.Email" class=form-control texto" aria-label = "Email" readonly />
                </div>

                <div class="input-group mt-2">
                 <span class = "input-group-text etiqueta" name ="NumeroTelefono" id="NumeroTelefono">NumeroTelefono</span>
                 <input asp-for = "Cliente.NumeroTelefono" class=form-control texto" aria-label = "Numero Telefono" readonly />
                </div>

                

                <div class="input-group mt-2">
                     <span type="file" name="files" id="files" multiple class="form-control" />
                   <input type="hidden" asp-for="Cliente.ImageUrl" class="text-danger" aria-label = "Imagen" readonly/>
                </div>
                <div class="col-12 form-control mt-2" style="border:none;">
                    
                    @if (!imagen.Equals(""))
                    {
                        <img id="image" src="@imagen"
                             class="card-img-top img-fluid rounded"
                             style="width: 200px; height: 150px;" />
                    }
                    else
                    {
                        <img id="image" src="~/imagenes/clientes/no-imagen.jpg"
                             class="card-img-bottom img-fluid rounded"
                             style="width: 200px; height: 150px;" />
                    }

              </div>

                
                 <div class="col-12 form-control mt-2" style="border:none;">
                

                <div class="form-group row pt-5">
                    <div class="col-4 offset-8">
                       
                        <div class="col">
                            <a asp-controller="ConsultaCliente"
                               asp-action="Index"
                               class="btn btn-outline-danger rounded-pill form-control">
                                <i class="fa fa-external-link"> Regresar</i>
                            </a>
                        </div>
                      
                            
                        
                                      </div>
                            </div>

                    </div>
               </div>
        </div>
    </div>

    <div class="card-body">

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    
    
    
    
    
    </script>
}