ProyectoCRPCC/Areas/Admin/Controllers/ConsultaCategoriaController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ProyectoCRPCC.Data.Repositorio.IRepositorio;
using ProyectoCRPCC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace WebEmbalaje.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ConsultaCategoriaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ConsultaCategoriaController(IUnidadTrabajo unidadTrabajo,
            IWebHostEnvironment hostEnvironment)
        {
            _unidadTrabajo = unidadTrabajo;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Categoria categoria = new Categoria();
            if (id == null)
            {
                //Esto es para crear una nueva bodega (insert)
                return View(categoria);
            }
            //actualizamos un registro Bodega existente
            categoria = _unidadTrabajo.Categoria.Obtener(id.GetValueOrDefault());
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }
    }
}

ProyectoCRPCC/Areas/Admin/Views/ConsultaCategoria/Index.cshtml
<br />
<br />
<br />
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h2 class="text-primary text-center">Lista de Categorías</h2>
        </div>
    </div>
   
</div>

<div class="p-4 border-rounded">
    <table id="tblDatos" class="table table-responsive-md table-bordered mt-2" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th style="max-width:35%;text-align:center;">Nombre</th>
                <th style="max-width: 25%;text-align: center;">Estado</th>
                <th style="max-width: 25%;text-align: center;">Operación</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/categoriaconsulta.js"></script>
}

ProyectoCRPCC/Areas/Admin/Views/ConsultaCategoria/Upsert.cshtml
@model ProyectoCRPCC.Models.Categoria

@{

    //Layout = "~/Views/Shared/_Layout.cshtml";
    var titulo = "Consulta de Categoria";
}
<style>
    input {
        max-width: 7000px;
        min-width: 100px;
    }

    .etiqueta {
        width: 200px;
        text-align: right;
    }
</style>
<form method="post">
    <div class="row p-3 border-0">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
    @if (Model.Id != 0)
    {
        // Actualizar
        titulo = "Consulta de Bodega";
    }
    <br />
    <br />
    <br />
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <hr>
                <div class="card-header-pills rounded-circle">
                    <h4 class="card-header-title text-center font-weight-bolder">
                        @titulo
                    </h4>
                </div>

                <h5 class="card-subtitle text-center">
                    Web CRPCC
                </h5>

                <hr>

                <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="Nombre" id="">Nombre: </span>
                    <input asp-for="Nombre" class="form-control" aria-label="Nombre" readonly>
                </div>
              
                <div class="input-group mt-2">
                    <span class="input-group-text etiqueta" name="Estado"
                          id="Estado">Estado:</span>
                    <select disabled asp-for="Estado" class="form-select" >
                        <option value=true>Activo</option>
                        <option value=false>Inactivo</option>
                    </select>
                </div>


                <div class="form-group row pt-5">
                    <div class="col-4 offset-8">
                       
                        <div class="col">
                            <a asp-controller="ConsultaCategoria"
                               asp-action="Index"
                               class="btn btn-outline-danger rounded-pill form-control">
                                <i class="fa fa-external-link"> Regresar</i>
                            </a>
                        </div>
                      
                            
                        
                    </div>
                </div>



            </div>
        </div>
    </div>


    <div class="card-body">

    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}